version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Australia/Sydney
    open-pull-requests-limit: 5
    groups:
      npm-development:
        dependency-type: development
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Australia/Sydney
    open-pull-requests-limit: 5
